domainmanager/domainmanager/urls.py
from django.contrib import admin
from django.urls import path, include
from domains.views import DashboardView

urlpatterns = [
    path('', DashboardView.as_view(), name='dashboard'),
    path('admin/', admin.site.urls),
    path('auth/', include('user_management.urls')),
    path('domains/', include('domains.urls')),
]

domainmanager/domains/urls.py
from argparse import Namespace
from django.urls import path, include
from .views import DashboardView, AddDomainsView, VerifyDomainView, DeleteDomainsView

app_name = "domains"

urlpatterns = [
    path('', DashboardView.as_view(), name="dashboard"),
    path('add-domain', AddDomainsView.as_view(), name="add-domain"),
    path('delete-domain', DeleteDomainsView.as_view(), name="delete-domain"),
    path('verify-domain', VerifyDomainView.as_view(), name="verify-domain"),
]

domainmanager/user_management/urls.py
from django.urls import path, include
from .views import Login, LogoutView, ForgotPassword, PasswordResetConfirmView

app_name = "user_management"

urlpatterns = [
    path('login/', Login.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("forgot-password/", ForgotPassword.as_view(), name="forgot-password"),
    path("reset/<uidb64>/<token>/<email>/", PasswordResetConfirmView.as_view(), name="reset"),
]

domainmanager/user_management/models.py
from django.db import models

# Create your models here.

domainmanager/user_management/forms.py
from django import forms

class AuthenticationForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField()

domainmanager/user_management/views.py
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from user_management.forms import AuthenticationForm
from django.contrib.auth import authenticate, login, logout
from django.views.generic import RedirectView
from django.views import View
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse, response
from django.conf import settings
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.template.loader import render_to_string
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import EmailMessage
from django.contrib.auth import get_user_model
from django.contrib.auth.views import (
    PasswordResetConfirmView as DjangoPasswordResetConfirmView,
)


class Login(View):
    def get(self, request, *args, **kwargs):
        return render(request, "login.html")

    def post(self, request):
        data = request.POST
        context = {}
        if data.get("email") and data.get("password"):
            user = self._attempt_login(data)
            
            if user:
                login(self.request, user)
                # change this url w.r.t what you want to redirect after successful login
                url = reverse('domains:dashboard')
                return HttpResponseRedirect(url)
            context["login_failed_message"] = "Incorrect Email or Password."
        else:
            context["login_failed_message"] = "Please Enter Email Address"

        return render(request, "login.html", context)

    def _attempt_login(self, data):
        authentication_form = AuthenticationForm(data)
        if authentication_form.is_valid():
            user = authenticate(**authentication_form.cleaned_data)
            if user is not None and user.is_active:
                return user

        return False


class LogoutView(View):
    def get(self, request):
        logout(request)
        return HttpResponseRedirect(settings.LOGIN_URL)


class ForgotPassword(View):
    def post(self, request):
        print("=== working ===")
        email = request.POST.get("email")
        User = get_user_model()
        associated_user = User.objects.filter(email=email).first()
        
        print("email: ", email)
        print("user: ", User)
        print("associated user: ", associated_user)
        
        if not associated_user:
            return JsonResponse({
                "status": False,
                "message": "Email address does not exist."
            })
        else:
            uid = urlsafe_base64_encode(force_bytes(associated_user.pk))
            token = default_token_generator.make_token(associated_user)
            reset_password_url = reverse(
                "user_management:reset",
                kwargs={"uidb64": uid, "token": token, "email": associated_user.email},
            )
            reset_password_url = self.request.build_absolute_uri(reset_password_url)

            context = {
                "user": associated_user,
                "reset_password_url": reset_password_url,
            }

            body = render_to_string("emails/reset_password.html", context)
            subject = render_to_string("emails/reset_password_subject.txt")
            to_email = associated_user.email
            from_email = settings.EMAIL_HOST_USER

            message = EmailMessage(subject, body, from_email, [to_email,])
            message.content_subtype = "html"
            message.send()

            return JsonResponse({
                "status": True,
                "message": "If you have an account associated with this email address, you will receive a password reset email. Please check your inbox."
            })


class PasswordResetConfirmView(DjangoPasswordResetConfirmView):
    success_url = reverse_lazy("user_management:login")
    template_name = "confirm_reset_password.html"

    def post(self, request, *args, **kwargs):
        User = get_user_model()
        user = User.objects.filter(email = kwargs.get('email')).first()
        if user:
            user.set_password(request.POST.get('password'))
            user.save()
            return JsonResponse({"status":200,"message":"Password has been changed successfully"})
        else:
            return JsonResponse({"status":400,"message":"User doesn't exist"})

domainmanager/user_management/templates/confirm_reset_password.html
{% load static %}
{% block content %}
    {% include 'user_management_header.html' %}
    <main class="main reset-password px-3 container mt-4">
        <div class="row g-0">
          <div class="col col-xl-4 mx-auto">
            <div class="card">
                <div class="card-body p-4 p-lg-5">
                    <img src="{% static 'images/logo_accounts.png' %}" alt="Your project name" class="site-logo img-fluid mb-5" />
                    <h1 class="h2 fw-bold mb-4">Reset your password</h1>
                    <p class="text-midnight mb-4">You've successfully verified your account. Enter new password below:</p>
                    {#TODO: This form doesnt validate#}
                    <form class="needs-validation" novalidate>
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="inputNewPass" class="form-label">Password</label>
                            <div class="position-relative">
                            <input
                            type="password"
                            name="new_password"
                            class="form-control"
                            placeholder="Password"
                            id="inputNewPass"
                            required
                            style="padding-right: 3rem;"/>
                            <i class="fa fa-eye togglePassword position-absolute top-50 start-100 translate-middle" id="togglePassword"></i>
                        </div>
                        <div class="invalid-feedback">Password is required.</div>
                        </div>
                        <div id="aggregationNameContainer" class="error-text d-flex align-items-center mt-2 d-none">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-exclamation-diamond text-danger" viewBox="0 0 16 16">
                            <path d="M6.95.435c.58-.58 1.52-.58 2.1 0l6.515 6.516c.58.58.58 1.519 0 2.098L9.05 15.565c-.58.58-1.519.58-2.098 0L.435 9.05a1.482 1.482 0 0 1 0-2.098L6.95.435zm1.4.7a.495.495 0 0 0-.7 0L1.134 7.65a.495.495 0 0 0 0 .7l6.516 6.516a.495.495 0 0 0 .7 0l6.516-6.516a.495.495 0 0 0 0-.7L8.35 1.134z"></path>
                            <path d="M7.002 11a1 1 0 1 1 2 0 1 1 0 0 1-2 0zM7.1 4.995a.905.905 0 1 1 1.8 0l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 4.995z"></path>
                            </svg>
                            <p class="text-danger my-0 mx-1" id="aggregationNameError"> Error</p>
                        </div>
                        <div class="mb-3">
                            <label for="inputConfirmPass" class="form-label">Confirm Password</label>
                            <div class="position-relative">
                            <input
                            type="password"
                            name="confirm_password"
                            placeholder="Password"
                            class="form-control"
                            id="inputConfirmPass"
                            required
                            style="padding-right: 3rem;"/>
                            <i class="fa fa-eye togglePassword position-absolute top-50 start-100 translate-middle" id="toggleConfirmPassword"></i>
                        </div>
                        <div class="invalid-feedback">Confirm password is required.</div>
                        </div>

                        <div id="aggregationNameContainer" class="error-text d-flex align-items-center mt-2 d-none">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-exclamation-diamond text-danger" viewBox="0 0 16 16">
                            <path d="M6.95.435c.58-.58 1.52-.58 2.1 0l6.515 6.516c.58.58.58 1.519 0 2.098L9.05 15.565c-.58.58-1.519.58-2.098 0L.435 9.05a1.482 1.482 0 0 1 0-2.098L6.95.435zm1.4.7a.495.495 0 0 0-.7 0L1.134 7.65a.495.495 0 0 0 0 .7l6.516 6.516a.495.495 0 0 0 .7 0l6.516-6.516a.495.495 0 0 0 0-.7L8.35 1.134z"></path>
                            <path d="M7.002 11a1 1 0 1 1 2 0 1 1 0 0 1-2 0zM7.1 4.995a.905.905 0 1 1 1.8 0l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 4.995z"></path>
                            </svg>
                            <p class="text-danger my-0 mx-1" id="aggregationNameError"> Error</p>
                        </div>
                        <button type="submit" class="btn btn-primary d-block w-100 mb-3" id="resetButton" onclick="updatePassword(event)">Reset Password</button>
                    </form>
                    <div class="text-center">
                        <a href="{% url 'user_management:login' %}" class="btn btn-link btn-back text-chambray fw-bolder">Back to Login</a>
                    </div>
                    <div class="alert alert-danger alert-dismissible fade mt-3 p-2 d-none show" id="error_validation" role="alert">
                        <strong id="stng_val_err"></strong>
                    </div>
                </div>
            </div>
          </div>
        </div>
    </main>
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js" integrity="sha512-s+xg36jbIujB2S2VKfpGmlC3T5V2TF3lY48DX7u2r9XzGzgPsa6wTpOQA7J9iffvdeBN0q9tKzRxVxw1JviZPg==" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <script>
        // Example starter JavaScript for disabling form submissions if there are invalid fields
        (function () {
        'use strict'

        // Fetch all the forms we want to apply custom Bootstrap validation styles to
        var forms = document.querySelectorAll('.needs-validation')

        // Loop over them and prevent submission
        Array.prototype.slice.call(forms)
            .forEach(function (form) {
            form.addEventListener('submit', function (event) {
                if (!form.checkValidity()) {
                event.preventDefault()
                event.stopPropagation()
                }

                form.classList.add('was-validated')
            }, false)
            })
        })()
        function updatePassword(event){
            event.preventDefault()
            var url_login = "{% url 'user_management:login' %}";
            if(/^\s+$/.test(event.target.form.new_password.value)){
                console.log("aaaaaaa")
                document.getElementById('stng_val_err').textContent = "Password must not be all white space"
                document.getElementById('error_validation').classList.remove('d-none')
                document.getElementById('error_validation').classList.add('d-block')
            }
            else if(event.target.form.new_password.value != event.target.form.confirm_password.value){
                console.log("bbbbbbb")
                document.getElementById('stng_val_err').textContent = "The password should be similar"
                document.getElementById('error_validation').classList.remove('d-none')
                document.getElementById('error_validation').classList.add('d-block')

            }else if(event.target.form.new_password.value.length < 8){
                console.log("ccccccc")
                document.getElementById('stng_val_err').textContent = "Password length should be greater then 8"
                document.getElementById('error_validation').classList.remove('d-none')
                document.getElementById('error_validation').classList.add('d-block')
            }else{
                console.log("dddddddd")
                var elementb64 = "{{view.kwargs.uidb64|safe}}"
                var elementtoken = "{{view.kwargs.token|safe}}"
                var elementEmail = "{{view.kwargs.email|safe}}"
                $.ajax({
                        method:'POST',
                        url: '/auth' + '/reset/' + elementb64 + "/" + elementtoken + "/" + elementEmail + "/",
                        data:{
                            password:document.getElementById('inputNewPass').value,
                            csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val()
                        },
                        success: function(data) {
                            if(data.status == 200){
                                window.location.href = url_login
                            } else if (!data.hasOwnProperty(status)){
                                document.getElementById('stng_val_err').textContent = "Link has been expired"
                                document.getElementById('error_validation').classList.remove('d-none')
                                document.getElementById('error_validation').classList.add('d-block')
                            }
                            else{
                                document.getElementById('stng_val_err').textContent = data.message
                                document.getElementById('error_validation').classList.remove('d-none')
                                document.getElementById('error_validation').classList.add('d-block')
                            }

                        },
                    });
            }
        }

const togglePassword = document.querySelector('#togglePassword');
const password = document.querySelector('#inputNewPass');

 togglePassword.addEventListener('click', function (e) {
   const type = password.getAttribute('type') === 'password' ? 'text' : 'password';
   password.setAttribute('type', type);
   this.classList.toggle('fa-eye-slash');
});

const toggleConfirmPassword = document.querySelector('#toggleConfirmPassword');
const confirm_password = document.querySelector('#inputConfirmPass');

toggleConfirmPassword.addEventListener('click', function (e) {
   const type = confirm_password.getAttribute('type') === 'password' ? 'text' : 'password';
   confirm_password.setAttribute('type', type);
   this.classList.toggle('fa-eye-slash');
});



    </script>
{% endblock content %}

domainmanager/user_management/templates/login.html
<!DOCTYPE html>
<html lang="en">
  {% include 'user_management_header.html' %}
  <body>
    <div class="page exam">
      <header class="header p-3 position-relative bg-white">
        <div class="container d-flex align-items-center">
          <img
            src="https://i.ibb.co/48bBCk1/logo.png"
            style="max-width: 60px"
            alt="Django App"
            class="site-logo"
          />
        </div>
      </header>

      <main class="main login container mt-4">
        <div class="row g-0">
          <div class="col col-xl-4 mx-auto">
            <div class="content">
              <div class="card border-0">
                <div class="card-body p-0">
                  <h1 class="h2 fw-bold mb-4">Login to your account</h1>
                  <form method="POST">
                    {% csrf_token %}
                    <div class="mb-4">
                      <label for="inputEmail" class="form-label">Email</label>
                      <input
                        type="email"
                        pattern='^(([^()\[\]\\.,;:\s@"]+(\.[^()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$'
                        name="email"
                        class="form-control"
                        id="inputEmail"
                        placeholder="example@gmail.com"
                        required
                      />
                    </div>
                    <div class="mb-3">
                      <label for="inputPassword" class="form-label"
                        >Password</label
                      >
                      <div class="position-relative">
                        <input
                          type="password"
                          name="password"
                          class="form-control"
                          id="inputPassword"
                          placeholder="password"
                          required
                          style="padding-right: 3rem"
                        />
                        <i
                          class="fa fa-eye togglePassword position-absolute top-50 start-100 translate-middle"
                          style="padding-right: 3rem"
                          id="togglePassword"
                        ></i>
                      </div>
                    </div>
                    <div class="d-flex justify-content-between mb-3">
                      <button
                        type="button"
                        class="btn btn-link btn-forgot-pass p-0"
                        id="forgot-pass-btn"
                        data-bs-toggle="modal"
                        data-bs-target="#forgotPassModal"
                      >
                        Forgot Password?
                      </button>
                    </div>
                    <button type="submit" class="btn btn-primary d-block w-100">
                      Login now
                    </button>
                  </form>

                  <p
                    class="flex-nowrap text-signup mt-4 mb-0 alert-danger d-none"
                  >
                    Error
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>

        <!-- Forgot Password Modal -->
        <div
          class="modal fade forgot-pass"
          id="forgotPassModal"
          tabindex="-1"
          aria-labelledby="forgotPassModalLabel"
          aria-hidden="true"
        >
          <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content py-5 px-4">
              <h3 class="modal-title mb-3" id="forgotPassModalLabel">
                Forgot your password?
              </h3>
              <p class="text-midnight mb-4">
                Please enter the email address you'd like your password reset
                information sent to
              </p>
              <form id="resetPasswordForm">
                <div class="mb-3">
                  <label for="inputPassEmail" class="form-label"
                    >Enter email address</label
                  >
                  <input
                    type="email"
                    name="email"
                    class="form-control validate-box"
                    id="inputPassEmail"
                    required
                  />
                  <br />
                </div>

                <div id="alertPlaceholder"></div>
                <button
                  type="submit"
                  class="btn btn-primary d-block w-100 mb-3"
                  id="requestButton"
                >
                  Request reset link
                </button>
              </form>
              <button
                type="button"
                class="btn btn-link btn-back text-chambray fw-bolder"
                data-bs-dismiss="modal"
              >
                Back to Login
              </button>
              <div
                class="alert"
                id="notification-forget"
                style="display: none"
              ></div>
            </div>
          </div>
        </div>
      </main>
    </div>

    <script
      src="https://code.jquery.com/jquery-3.6.0.min.js"
      integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
      integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
      integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
      crossorigin="anonymous"
    ></script>


    <script>
      $(document).ready(function () {
        $('#resetPasswordForm').on('submit', function(e){
          e.preventDefault()
        is_valid = validate();
        if (is_valid == true){
          $("#loader").removeClass("d-none");
          $("#loader").addClass("d-flex");
          $.ajax({
            method:'POST',
            url: "{% url 'user_management:forgot-password' %}",
            headers: {"X-CSRFToken": "{{csrf_token}}"},
            data:{
              email:$('#inputPassEmail').val()
            },
            success: function(data){
                if (!data.status){
                  $("#loader").removeClass("d-flex");
                  $("#loader").addClass("d-none");
                  msg = data.message
                  status = "danger"
                  app_alert(msg, status);
                }
                else{
                  msg = data.message
                  status = "success"
                  app_alert(msg, status);
                  $("#loader").removeClass("d-flex");
                  $("#loader").addClass("d-none");
                }
            },
        });
        }else {
          msg = "Please enter a valid email address."
          status = "danger"
          app_alert(msg, status);
        }
        });
      });

      $("#forgot-pass-btn").click(function () {
        $('#resetPasswordForm').trigger("reset");
      });

      const validateEmail = (email) => {
        return String(email)
          .toLowerCase()
          .match(
            /^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/
          );
      };

      const validate = () => {
        const email = $("#inputPassEmail").val();
    
        if (validateEmail(email)) {
          return true;
        } else {
          return false;
        }
      };

      function app_alert(message, type) {
        $('#notification-forget').text(message);
        $('#notification-forget').removeClass();
        $('#notification-forget').addClass('alert alert-'+type);
        $('#notification-forget').show()
        setTimeout(()=>{
          $('#notification-forget').hide()
          },3000);
      }

      const togglePassword = document.querySelector('#togglePassword');
      const password = document.querySelector('#inputPassword');

      togglePassword.addEventListener('click', function (e) {
        const type = password.getAttribute('type') === 'password' ? 'text' : 'password';
        password.setAttribute('type', type);
        this.classList.toggle('fa-eye-slash');
    });

    </script>
  </body>
</html>

domainmanager/user_management/templates/user_management_header.html
{% load static %}
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Django App</title>
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
    href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,300;0,400;0,500;0,700;1,400&display=swap"
    rel="stylesheet"
    />
    <link
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
    rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
    crossorigin="anonymous"
    />
    <link
    rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
</head>