domainmanager/domainmanager/urls.py
from django.contrib import admin
from django.urls import path, include
from domains.views import DashboardView

urlpatterns = [
    path('', DashboardView.as_view(), name='dashboard'),
    path('admin/', admin.site.urls),
    path('auth/', include('user_management.urls')),
    path('domains/', include('domains.urls')),
]

domainmanager/domains/urls.py
from argparse import Namespace
from django.urls import path, include
from .views import DashboardView, AddDomainsView, VerifyDomainView, DeleteDomainsView

app_name = "domains"

urlpatterns = [
    path('', DashboardView.as_view(), name="dashboard"),
    path('add-domain', AddDomainsView.as_view(), name="add-domain"),
    path('delete-domain', DeleteDomainsView.as_view(), name="delete-domain"),
    path('verify-domain', VerifyDomainView.as_view(), name="verify-domain"),
]

domainmanager/user_management/urls.py
from django.urls import path, include
from .views import Login, LogoutView, ForgotPassword, PasswordResetConfirmView

app_name = "user_management"

urlpatterns = [
    path('login/', Login.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("forgot-password/", ForgotPassword.as_view(), name="forgot-password"),
    path("reset/<uidb64>/<token>/<email>/", PasswordResetConfirmView.as_view(), name="reset"),
]

domainmanager/domains/models.py
import uuid
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _
from domains.managers import UserManager


class User(AbstractUser):
    username = models.CharField(max_length=50, blank=True, null=True, unique=True)
    email = models.EmailField(_("email address"), unique=True)
    account = models.ForeignKey("domains.Account", on_delete=models.CASCADE, db_column="account_id", default=None, null=True, blank=True)
    objects = UserManager()
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ['username', 'first_name', 'last_name']

    def __str__(self):
        return self.email


class Account(models.Model):
    STATUS_CHOICES = (
        ('1', 'Pending'),
        ('2', 'Verified'),
        ('3', 'Disabled'),
        ('4', 'Deleted')
    )
    account_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    source_prefix_id = models.CharField(max_length=6, unique=True)
    account_name = models.CharField(max_length=255)
    owner = models.CharField(max_length=255)
    domain_cap = models.IntegerField(default=2)
    status = models.CharField(choices=STATUS_CHOICES, max_length=255, default='1')

    def __str__(self):
        return self.account_name

    class Meta:
        verbose_name_plural = "Accounts"

class Domain(models.Model):
    SOURCE_TYPE_CHOICES = (
        ('1', 'DNS'),
        ('2', 'DB'),
        ('3', 'Mirror')
    )
    STATUS_CHOICES = (
        ('1', 'Pending'),
        ('2', 'Verified'),
        ('3', 'Disabled'),
        ('4', 'Deleted'),
        ('5', 'Enabled'),
    )
    domain_id = models.UUIDField(primary_key = True, default = uuid.uuid4, editable = False)
    domain_name = models.CharField(max_length=255)
    source_prefix = models.CharField(max_length=8, unique=True)
    source_type = models.CharField(choices=SOURCE_TYPE_CHOICES, max_length=255, default='1')
    status = models.CharField(choices=STATUS_CHOICES, max_length=255, default='1')
    account = models.ForeignKey(Account, on_delete=models.CASCADE)

    def __str__(self):
        return self.domain_name

domainmanager/domains/views.py
from multiprocessing import context
from django.shortcuts import render
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import User, Account, Domain
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from django.urls import reverse, reverse_lazy
import string
import random
import dns.resolver
import ast


class DashboardView(LoginRequiredMixin, View):
    def get(self, request):
        context = {}
        user = User.objects.filter(pk=request.user.id).first()
        associated_domains = Domain.objects.filter(account=user.account).exclude(status='4')
        domains=[]
        for domain in associated_domains:
            domains.append(domain)

        context.update({
            'domains': domains
        })

        return render(request, "dashboard.html", context)


class AddDomainsView(LoginRequiredMixin, View):
    def get(self, request):
        return render(request, "add_domain.html")

    def post(self, request):
        domain_name = request.POST.get('domain_name')
        user = User.objects.filter(pk=request.user.id).first()
        source_prefix = '_' + id_generator()
        domains_count = Domain.objects.filter(account=user.account).exclude(status='4').count()

        if domains_count >= user.account.domain_cap:
            return JsonResponse({
                "status": False,
                "status_code": 301,
                "message": "Domain cap exceeds! You can't add more domains."
            })

        domain = Domain.objects.create(
            domain_name=domain_name,
            source_prefix=source_prefix.lower(),
            account=user.account
        )
        spf_domain = domain.source_prefix + "." + domain.domain_name
        return JsonResponse({
            "status": True,
            "status_code": 200,
            "message": "Domain added successfully.",
            "domain": spf_domain,
            "domain_name": domain.domain_name,
            "source_prefix": domain.source_prefix,
        })


class VerifyDomainView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        return render(request, "domain_verify.html")

    def post(self, request, *args, **kwargs):
        is_verify_page = request.POST.get('is_verify_page')
        is_spf = False
        if is_verify_page == 'True':
            domain_to_verify = request.POST.get('domain_to_verify') 
            domain_prefix = domain_to_verify.split('.')[0]
            associated_domain = Domain.objects.filter(source_prefix=domain_prefix).first()
            try:
                result = dns.resolver.resolve(domain_to_verify, 'TXT')
                for val in result:
                    if ast.literal_eval(val.to_text()).startswith("v=spf1"):
                        is_spf = True
                        break

                if is_spf == True:
                    associated_domain.update(status='2') # status=2 is verified
                    return JsonResponse({
                        "status": True,
                        "message": "Domain Verified"
                    })
                else:
                    return JsonResponse({
                        "status": True,
                        "message": "Domain is not verified"
                    })
            except:
                return JsonResponse({
                    "status": False,
                    "message": "The DNS query name does not exist"
                })
        else:
            domain_id = request.POST.get('domain_id')
            domain = Domain.objects.filter(domain_id=domain_id)
            prefix_domain = domain[0].source_prefix + '.' + domain[0].domain_name
            try:
                result = dns.resolver.resolve(prefix_domain, 'TXT')
                for val in result:
                    if ast.literal_eval(val.to_text()).startswith("v=spf1"):
                        is_spf = True
                        break

                if is_spf == True:
                    domain.update(status='2') # status=2 is verified
                    return JsonResponse({
                        "status": True,
                        "message": "Domain Verified"
                    })
                else:
                    return JsonResponse({
                        "status": True,
                        "message": "Domain is not verified"
                    })
            except:
                return JsonResponse({
                    "status": False,
                    "message": "The DNS query name does not exist"
                })


class DeleteDomainsView(LoginRequiredMixin, View):
    def post(self, request):
        is_disable = request.POST.get('is_disable')
        is_enable = request.POST.get('is_enable')
        domain_id = request.POST.get('domain_id')

        if is_disable == 'True':
            try:
                domain = Domain.objects.filter(domain_id=domain_id)
                domain.update(status='3')
                return JsonResponse({
                    "status": True,
                    "message": "Domain disabled!"
                })
            except:
                return JsonResponse({
                    "status": False,
                    "message": "Something went wrong!"
                })
        elif is_enable == 'True':
            try:
                domain = Domain.objects.filter(domain_id=domain_id)
                domain.update(status='5')
                return JsonResponse({
                    "status": True,
                    "message": "Domain Enabled successfully!"
                })
            except:
                return JsonResponse({
                    "status": False,
                    "message": "Something went wrong!"
                })
        else:
            try:
                domain = Domain.objects.filter(domain_id=domain_id)
                domain.update(status='4')
                return JsonResponse({
                    "status": True,
                    "message": "Domain deleted successfully"
                })
            except:
                return JsonResponse({
                    "status": False,
                    "message": "Something went wrong!"
                })



############################################################
#################### PRIVATE FUNCTIONS #####################
############################################################

# Function to generate 7 digits random string
def id_generator(size=7, chars=string.ascii_uppercase + string.digits):
    return ''.join(random.choice(chars) for _ in range(size))

domainmanager/domains/templates/add_domain.html
{% extends 'base.html' %}
{% block body %}
{% include 'header.html' %}

<main>
  <section class="domain-sec pt-5 mt-5">
    <div class="container">
      <div class="row">
        <div class="col-sm-12">
            {% csrf_token %}
            <label>
              <span>Domain Name</span>
              <input type="text" id="domain-name" name="domain" required/>
              <a type="button" id="add-domain-btn" class="domain-btn">add domain</a>
            </label>
        </div>
      </div>
    </div>
  </section>
</main>


<!-- Warning Modal -->
<div id="verify_modal" class="warning_modal">
  <div class="verify-sec">
    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" onclick="document.getElementById('verify_modal').style.display='none'"></button>
      <div class="container-fluid p-0">
          <div class="row justify-content-center">
              <div id="verify-modal-div" class="col-sm-12"></div>
              <div class="col-sm-12">
                <p>This will be the source of truth for your SPF record moving forward.</p>
              </div>
              <div class="col-sm-12">
                  <label for="">
                      <input type="text" id="verify-domain-input" name="domain" placeholder="_3ed4r.Abc.com" value="">
                      <a type="submit" name="submit" class="submit" id="add-verify-domain">Verify Domain</a>
                  </label>
              </div>
          </div>
      </div>
  </div>
</div>
<!-- Warning Modal End -->

<script>
    $(document).ready(function () {
        $("#add-domain-btn").on("click", function (e) {
          e.preventDefault();
          var domain_name = $('#domain-name').val();
          if (!domain_name){
            alert("Domain name field can't be empty");
          }
          else{
            $.ajax({
              method: "POST",
              url: "{% url 'domains:add-domain' %}",
              data: {
                domain_name: $('#domain-name').val(),
                csrfmiddlewaretoken: $("input[name=csrfmiddlewaretoken]").val(),
              },
              success: function (data) {
                if (data.status == true) {
                  var domain = data.domain;
                  var domain_name = data.domain_name;
                  var source_prefix = data.source_prefix;
                  document.getElementById('verify_modal').style.display='block';
                  $('#verify-domain-input').val(data.domain);
                  var verify_modal_div = $('#verify-modal-div');
                  var paragraph = document.createElement("p");
                  paragraph.textContent = `In order to complete this process, copy your existing SPF from ${domain_name} to 
                  subdomain ${source_prefix}.${domain_name} and click ‘verify domain’`;
                  verify_modal_div.append(paragraph);
                } else if (data.status == false) {
                  alert(data.message);
                  window.location.href = "{% url 'domains:dashboard' %}";
                }
              },
            });
        }
        });

        $("#add-verify-domain").on("click", function (e) {
          e.preventDefault();
          $.ajax({
            method: "POST",
            url: "{% url 'domains:verify-domain' %}",
            data: {
              is_verify_page: 'True',
              domain_to_verify: $('#verify-domain-input').val(),
              csrfmiddlewaretoken: $("input[name=csrfmiddlewaretoken]").val(),
            },
            success: function (data) {
              if (data.status == true) {
                alert(data.message);
                window.location.href = "{% url 'domains:dashboard' %}";
              } else if (data.status == false) {
                alert(data.message);
                window.location.href = "{% url 'domains:dashboard' %}";
              }
            },
          });
        });

      });
</script>

{% endblock body %}

domainmanager/domains/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Domain Dashboard{% endblock title %}</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,300;0,400;0,500;0,700;1,400&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js" integrity="sha512-s+xg36jbIujB2S2VKfpGmlC3T5V2TF3lY48DX7u2r9XzGzgPsa6wTpOQA7J9iffvdeBN0q9tKzRxVxw1JviZPg==" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    {% block head %}{% endblock head %}
</head>
<body>

    {% block body %}{% endblock body %}
    {% block scripts %}{% endblock scripts %}

</body>
</html>

domainmanager/domains/templates/dashboard.html
{% extends 'base.html' %}
{% block body %}
{% include 'header.html' %}

<main>
  {% csrf_token %}
  <section class="table-sec pt-5 mt-5">
    <div class="container">
      <div class="row">
        <div class="col-sm-12">
            <div class="table-responsive">
                <table class="table pt-5 table-bordered">
                    <thead>
                    <tr class="dark-blue">
                        <th scope="col">Domain</th>
                        <th scope="col">Source Prefix</th>
                        <th scope="col">Status</th>
                        <th scope="col">Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr class="light-blue">
                        {% for domain in domains %}
                        <td>{{ domain.domain_name }}</td>
                        <td>{{ domain.source_prefix }}</td>
                        {% if domain.get_status_display == 'Verified' or domain.get_status_display == 'Enabled' %}
                        <td>Active</td>
                        {% else %}
                        <td>{{domain.get_status_display}}</td>
                        {% endif %}
                        {% if domain.get_status_display == 'Verified' %}
                        <td>
                        <button type="button" class="disable-domain" data-domainid="{{domain.domain_id}}">Disable</button>
                        <a
                            href="javascript:void(0)"
                            id="{{domain.domain_id}}"
                            type="button"
                            class="dlt-btn"
                            data-domainid="{{domain.domain_id}}"
                            onclick="deleteFunc('{{domain.domain_id}}')"
                            >Delete</a
                        >
                        </td>
                        {% endif %} {% if domain.get_status_display == 'Pending' %}
                        <td>
                        <a
                            href="#"
                            id="{{domain.domain_id}}"
                            class="verify-btn"
                            type="button"
                            data-domainid="{{domain.domain_id}}"
                            >Verify</a
                        >
                        <a
                            href="#"
                            id="{{domain.domain_id}}"
                            type="button"
                            class="dlt-btn"
                            data-domainid="{{domain.domain_id}}"
                            onclick="deleteFunc('{{domain.domain_id}}')"
                            >Delete</a
                        >
                        </td>
                        {% endif %} {% if domain.get_status_display == 'Disabled' %}
                        <td>
                        <button type="button" class="enable-domain" data-domainid="{{domain.domain_id}}">Enable</button>
                        <a
                            href="#"
                            id="{{domain.domain_id}}"
                            type="button"
                            class="dlt-btn"
                            data-domainid="{{domain.domain_id}}"
                            onclick="deleteFunc('{{domain.domain_id}}')"
                            >Delete</a
                        >
                        </td>

                        {% endif %} {% if domain.get_status_display == 'Enabled' %}
                        <td>
                          <button type="button" class="disable-domain" data-domainid="{{domain.domain_id}}">Disable</button>
                        <a
                            href="#"
                            id="{{domain.domain_id}}"
                            type="button"
                            class="dlt-btn"
                            data-domainid="{{domain.domain_id}}"
                            onclick="deleteFunc('{{domain.domain_id}}')"
                            >Delete</a
                        >
                        </td>

                        {% endif %} {% if domain.get_status_display == 'Deleted' %}
                        <td></td>
                        {% endif %}
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
      </div>
    </div>
  </section>
</main>

<!-- Warning Modal -->
<div id="warning_modal" class="warning_modal">
    <div class="inner_content">
        <h1>Warning</h1>
        <p>if domain is deleted, the SPF record will no longer respond</p>
        <div class="clearfix">
            <button type="button" id="delete-btn" class="deletebtn">Delete</button>
            <button type="button" onclick="document.getElementById('warning_modal').style.display='none'" class="cancelbtn">Cancel</button>
        </div>
    </div>
</div>
<!-- Warning Modal End -->

<script>
    var global_domain_id = ""

    function deleteFunc(domain_id){
        global_domain_id = domain_id;
        document.getElementById('warning_modal').style.display='block';
    }

  $(document).ready(function () {
    $(".verify-btn").on("click", function (e) {
      e.preventDefault();
      $.ajax({
        method: "POST",
        url: "{% url 'domains:verify-domain' %}",
        data: {
          is_verify_page: 'False',
          domain_id: $(this).attr("data-domainid"),
          csrfmiddlewaretoken: $("input[name=csrfmiddlewaretoken]").val(),
        },
        success: function (data) {
          if (data.status == true) {
            alert("domain successfully verified");
            window.location.href = "{% url 'domains:dashboard' %}";
          } else if (data.status == false) {
            alert(data.message);
          }
        },
      });
    });
  });

  $(document).ready(function () {
    $("#delete-btn").on("click", function (e) {
      e.preventDefault();
      $.ajax({
        method: "POST",
        url: "{% url 'domains:delete-domain' %}",
        headers: { "X-CSRFToken": "{{ csrf_token }}" },
        data: {
          is_disable: 'False',
          is_enable: 'False',
          domain_id: global_domain_id,
        },
        success: function (data) {
          if (data.status == true) {
            window.location.href = "{% url 'domains:dashboard' %}";
          } else if (data.status == false) {
            alert(data.message);
          }
        },
      });
    });

    $(".disable-domain").on("click", function (e) {
      var id = $(this).attr("data-domainid");
      console.log("domain_id: ", id);
      e.preventDefault();
      $.ajax({
        method: "POST",
        url: "{% url 'domains:delete-domain' %}",
        headers: { "X-CSRFToken": "{{ csrf_token }}" },
        data: {
          is_disable: 'True',
          is_enable: 'False',
          domain_id: $(this).attr("data-domainid"),
        },
        success: function (data) {
          if (data.status == true) {
            alert(data.message);
            window.location.href = "{% url 'domains:dashboard' %}";
          } else if (data.status == false) {
            alert(data.message);
          }
        },
      });
    });

    $(".enable-domain").on("click", function (e) {
      e.preventDefault();
      $.ajax({
        method: "POST",
        url: "{% url 'domains:delete-domain' %}",
        headers: { "X-CSRFToken": "{{ csrf_token }}" },
        data: {
          is_enable: 'True',
          is_disable: 'False',
          domain_id: $(this).attr("data-domainid"),
        },
        success: function (data) {
          if (data.status == true) {
            alert(data.message);
            window.location.href = "{% url 'domains:dashboard' %}";
          } else if (data.status == false) {
            alert(data.message);
          }
        },
      });
    });

  });
</script>

{% endblock body %}

domainmanager/domains/templates/header.html
{% load static %}
{% csrf_token %}
<header class="header bg-white pt-3">
    <div class="container">
        <div class="row">
            <nav class="navbar navbar-expand-lg navbar-light">
                <div class="container-fluid container-fluid p-0">
                  <a class="navbar-brand" href="{% url 'domains:dashboard' %}"><img src="{% static 'images/logo_accounts.png' %}"  style="max-width: 80px;" alt="Django App logo" class="site-logo" /></a>
                  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                  </button>
                  <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
                    <ul class="navbar-nav">
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'domains:add-domain' %}">Add Domain</a>
                      </li>
                      <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="true">
                          Menu
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                          <li><a class="dropdown-item" href="{% url 'domains:dashboard' %}">Domain Names</a></li>
                          {% if user.is_superuser %}
                          <li><a class="dropdown-item" href="#">Account</a></li>
                          <li><a class="dropdown-item" href="#">User Management</a></li>
                          <li><a class="dropdown-item" href="#">Support</a></li>
                          {% endif %}
                          <li><a class="dropdown-item" href="{% url 'user_management:logout' %}">Logout</a></li>
                        </ul>
                      </li>
                    </ul>
                  </div>
                </div>
            </nav>
        </div>
    </div>
</header>